### API - 1 Scenrio -1 
GET http://localhost:3000/todos/?status=TO%20DO

### API - 1  Scenario 2 

GET http://localhost:3000/todos/?priority=HIGH

### API - 1  Scenario 3 
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS 

### API - 1  Scenario 3 
GET http://localhost:3000/todos/?search_q=JS

### API - 2  Scenario 1 
GET http://localhost:3000/todos/7/

### API - 3 
POST http://localhost:3000/todos/ 
Content-Type: application/json 

{
   "id": 14,
  "todo": "Radha Soul of Khana",
  "priority": "LOW",
  "status": "TO DO"
}

### API - 4  Scenario 1 

PUT http://localhost:3000/todos/12/
Content-Type: application/json

{
    "status" : "IN PROGRESS"
}

###
DELETE http://localhost:3000/todos/7/
